---
version: 2.1

references:
  images:
    go: &GOLANG_IMAGE docker.mirror.hashicorp.services/cimg/go:1.17.7

  paths:
    test-results: &TEST_RESULTS_DIR /tmp/test-results

  environment: &ENVIRONMENT
    TEST_RESULTS_DIR: *TEST_RESULTS_DIR
    GOLANG_IMAGE: *GOLANG_IMAGE
    GOLANGCI_LINT_VERSION: "v1.39.0"

jobs:
  lint:
    docker:
      - image: *GOLANG_IMAGE
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      # Install command from https://golangci-lint.run/usage/install/
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}
      - run: make lint

  gomod:
    docker:
      - image: *GOLANG_IMAGE
    steps:
      - checkout
      - run:
          name: go mod tidy
          command: |
            make mod
            if ! git diff --exit-code; then
              echo "Git directory has go.mod or go.sum changes"
              exit 1
            fi
  build:
    docker:
      - image: *GOLANG_IMAGE
    steps:
      - checkout
      - run: make build

  go-test:
    docker:
      - image: *GOLANG_IMAGE
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS_DIR/go-test && make test

      # Store the results so they display nicely in CircleCI.
      - store_artifacts:
          path: *TEST_RESULTS_DIR
      - store_test_results:
          path: *TEST_RESULTS_DIR

workflows:
  version: 2
  test-workflow:
    jobs:
      - lint
      - gomod
      - build:
          requires:
            - lint
            - gomod
      - go-test:
          requires:
            - lint
            - gomod
